name: Push Docker image to AWS ECR

on:
  push:
    branches:
      - master

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag Docker image
      id: build-image
      run: |
        docker build -t node-auth-app:${{ github.sha }} .
        docker tag node-auth-app:${{ github.sha }} node-auth-app:latest

    - name: Push Docker image to ECR
      id: push-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker push node-auth-app:latest
